In [39]:
!apt-get -qq update
!apt-get -qq install -y postgresql postgresql-contrib
!pip install -q sqlalchemy psycopg2-binary pandas

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)

In [76]:
!service postgresql start
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
!sudo -u postgres psql -c "CREATE DATABASE colab_db;" 2>/dev/null || true

[ OK ]
ALTER ROLE

In [77]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/colab_db"
)

In [78]:

with engine.connect() as conn:
    result = conn.execute(
        text("SELECT version(), current_database()")
    )
    print(result.fetchone())

('PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit', 'colab_db')

In [79]:

from pathlib import Path
import subprocess

REPO_URL = (
    "https://github.com/Serhii-Malichenko/"
    "goit-rdb-hw-04-DML-DDL-_Serhii_Malichenko.git"
)
PROJECT_DIR = Path("/content/homework-4")

if not PROJECT_DIR.exists():
    subprocess.run(
        ["git", "clone", REPO_URL, str(PROJECT_DIR)],
        check=True
    )

DATA_DIR = PROJECT_DIR / "data"

expected_files = [
    "olist_customers_dataset.csv",
    "olist_order_items_dataset.csv",
    "olist_order_reviews_dataset.csv",
    "olist_orders_dataset.csv",
    "olist_products_dataset.csv",
    "olist_sellers_dataset.csv",
]

missing_files = [
    filename
    for filename in expected_files
    if not (DATA_DIR / filename).exists()
]

if missing_files:
    raise FileNotFoundError(f"Missing CSV files: {missing_files}")

print(f"Data directory: {DATA_DIR}")
print(f"CSV files found: {len(expected_files)}")

Data directory: /content/homework-4/data
CSV files found: 6

In [80]:

from pathlib import Path
import pandas as pd

# CSV files are loaded automatically from the public GitHub repository
data_dir = Path("/content/homework-4/data")

csv_files = {
    "raw_customers": "olist_customers_dataset.csv",
    "raw_orders": "olist_orders_dataset.csv",
    "raw_order_items": "olist_order_items_dataset.csv",
    "raw_products": "olist_products_dataset.csv",
    "raw_sellers": "olist_sellers_dataset.csv",
    "raw_order_reviews": "olist_order_reviews_dataset.csv",
}

# Check that all files are available
missing_files = [
    filename
    for filename in csv_files.values()
    if not (data_dir / filename).exists()
]

if missing_files:
    raise FileNotFoundError(
        f"Missing CSV files: {missing_files}"
    )

# Load CSV files into PostgreSQL
for table_name, filename in csv_files.items():
    df = pd.read_csv(data_dir / filename)

    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False
    )

    print(f"{table_name}: {len(df)} rows loaded")

print("\nAll six CSV files loaded successfully.")

raw_customers: 220 rows loaded
raw_orders: 320 rows loaded
raw_order_items: 475 rows loaded
raw_products: 45 rows loaded
raw_sellers: 18 rows loaded
raw_order_reviews: 270 rows loaded

All six CSV files loaded successfully.

In [81]:

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT 'raw_customers' AS table_name, COUNT(*) AS row_count
        FROM raw_customers
        UNION ALL
        SELECT 'raw_orders', COUNT(*) FROM raw_orders
        UNION ALL
        SELECT 'raw_order_items', COUNT(*) FROM raw_order_items
        UNION ALL
        SELECT 'raw_products', COUNT(*) FROM raw_products
        UNION ALL
        SELECT 'raw_sellers', COUNT(*) FROM raw_sellers
        UNION ALL
        SELECT 'raw_order_reviews', COUNT(*) FROM raw_order_reviews
        ORDER BY table_name
    """))

    print(pd.DataFrame(result.fetchall(),
                       columns=result.keys()).to_string(index=False))

       table_name  row_count
    raw_customers        220
  raw_order_items        475
raw_order_reviews        270
       raw_orders        320
     raw_products         45
      raw_sellers         18

In [82]:

ddl = """
CREATE TABLE IF NOT EXISTS olist_customers (
    customer_id TEXT PRIMARY KEY,
    customer_unique_id TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city TEXT,
    customer_state CHAR(2)
);

CREATE TABLE IF NOT EXISTS olist_sellers (
    seller_id TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city TEXT,
    seller_state CHAR(2)
);

CREATE TABLE IF NOT EXISTS olist_products (
    product_id TEXT PRIMARY KEY,
    product_category_name TEXT,
    product_name_length INTEGER,
    product_description_length INTEGER,
    product_photos_qty INTEGER,
    product_weight_g INTEGER,
    product_length_cm INTEGER,
    product_height_cm INTEGER,
    product_width_cm INTEGER
);

CREATE TABLE IF NOT EXISTS olist_orders (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status TEXT NOT NULL CHECK (
        order_status IN (
            'created', 'approved', 'invoiced', 'processing',
            'shipped', 'delivered', 'unavailable', 'canceled'
        )
    ),
    order_purchase_timestamp TIMESTAMP,
    order_approved_at TIMESTAMP,
    order_delivered_carrier_date TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS olist_order_items (
    order_id TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id INTEGER NOT NULL,
    product_id TEXT NOT NULL REFERENCES olist_products(product_id),
    seller_id TEXT NOT NULL REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    freight_value NUMERIC(12,2) NOT NULL CHECK (freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);

CREATE TABLE IF NOT EXISTS olist_order_reviews (
    review_row_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    review_id TEXT,
    order_id TEXT NOT NULL REFERENCES olist_orders(order_id),
    review_score INTEGER CHECK (review_score BETWEEN 1 AND 5),
    review_comment_title TEXT,
    review_comment_message TEXT,
    review_creation_date TIMESTAMP,
    review_answer_timestamp TIMESTAMP
);
"""

with engine.begin() as conn:
    conn.execute(text(ddl))

print("Typed tables created successfully.")

Typed tables created successfully.

## Data preparation: Raw and Typed Layers

In [83]:

load_typed_sql = """
TRUNCATE TABLE
    olist_order_reviews,
    olist_order_items,
    olist_orders,
    olist_products,
    olist_sellers,
    olist_customers
RESTART IDENTITY CASCADE;

INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    NULLIF(customer_zip_code_prefix::TEXT, '')::INTEGER,
    customer_city,
    customer_state
FROM raw_customers;

INSERT INTO olist_sellers
SELECT
    seller_id,
    NULLIF(seller_zip_code_prefix::TEXT, '')::INTEGER,
    seller_city,
    seller_state
FROM raw_sellers;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    NULLIF(product_name_lenght::TEXT, '')::INTEGER,
    NULLIF(product_description_lenght::TEXT, '')::INTEGER,
    NULLIF(product_photos_qty::TEXT, '')::INTEGER,
    NULLIF(product_weight_g::TEXT, '')::INTEGER,
    NULLIF(product_length_cm::TEXT, '')::INTEGER,
    NULLIF(product_height_cm::TEXT, '')::INTEGER,
    NULLIF(product_width_cm::TEXT, '')::INTEGER
FROM raw_products;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    NULLIF(order_purchase_timestamp::TEXT, '')::TIMESTAMP,
    NULLIF(order_approved_at::TEXT, '')::TIMESTAMP,
    NULLIF(order_delivered_carrier_date::TEXT, '')::TIMESTAMP,
    NULLIF(order_delivered_customer_date::TEXT, '')::TIMESTAMP,
    NULLIF(order_estimated_delivery_date::TEXT, '')::TIMESTAMP
FROM raw_orders;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    NULLIF(shipping_limit_date::TEXT, '')::TIMESTAMP,
    price::NUMERIC(12,2),
    freight_value::NUMERIC(12,2)
FROM raw_order_items;

INSERT INTO olist_order_reviews (
    review_id,
    order_id,
    review_score,
    review_comment_title,
    review_comment_message,
    review_creation_date,
    review_answer_timestamp
)
SELECT
    review_id,
    order_id,
    NULLIF(review_score::TEXT, '')::INTEGER,
    review_comment_title,
    review_comment_message,
    NULLIF(review_creation_date::TEXT, '')::TIMESTAMP,
    NULLIF(review_answer_timestamp::TEXT, '')::TIMESTAMP
FROM raw_order_reviews;
"""

with engine.begin() as conn:
    conn.execute(text(load_typed_sql))

print("Data loaded into all typed tables.")

Data loaded into all typed tables.

### Data integrity validation

In [84]:

validation_sql = """
SELECT 'customers' AS entity,
       (SELECT COUNT(*) FROM raw_customers) AS raw_rows,
       (SELECT COUNT(*) FROM olist_customers) AS typed_rows

UNION ALL

SELECT 'orders',
       (SELECT COUNT(*) FROM raw_orders),
       (SELECT COUNT(*) FROM olist_orders)

UNION ALL

SELECT 'order_items',
       (SELECT COUNT(*) FROM raw_order_items),
       (SELECT COUNT(*) FROM olist_order_items)

UNION ALL

SELECT 'products',
       (SELECT COUNT(*) FROM raw_products),
       (SELECT COUNT(*) FROM olist_products)

UNION ALL

SELECT 'sellers',
       (SELECT COUNT(*) FROM raw_sellers),
       (SELECT COUNT(*) FROM olist_sellers)

UNION ALL

SELECT 'order_reviews',
       (SELECT COUNT(*) FROM raw_order_reviews),
       (SELECT COUNT(*) FROM olist_order_reviews)

ORDER BY entity;
"""

with engine.connect() as conn:
    result = conn.execute(text(validation_sql))
    validation_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

validation_df["counts_match"] = (
    validation_df["raw_rows"] == validation_df["typed_rows"]
)

display(validation_df)

          entity  raw_rows  typed_rows  counts_match
0      customers       220         220          True
1    order_items       475         475          True
2  order_reviews       270         270          True
3         orders       320         320          True
4       products        45          45          True
5        sellers        18          18          True

## Data Manipulation Language (DML)

### Seller delivery alerts

**Business question:** Which seller has the highest number of late deliveries?

We create a table to store seller alerts. A late delivery is defined as an order delivered after its estimated delivery date. The query will identify the seller with the highest number of late deliveries and insert an alert record using `INSERT ... RETURNING`.

In [85]:

create_alerts_sql = """
CREATE TABLE IF NOT EXISTS seller_alerts (
    alert_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seller_id TEXT NOT NULL REFERENCES olist_sellers(seller_id),
    late_orders_count INTEGER NOT NULL CHECK (late_orders_count > 0),
    alert_message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

with engine.begin() as conn:
    conn.execute(text(create_alerts_sql))

print("Seller alerts table created successfully.")

Seller alerts table created successfully.

**Insert an alert using `INSERT ... RETURNING`**

The query counts late delivered orders for each seller. It uses `COUNT(DISTINCT order_id)` to avoid counting the same order more than once for a seller. The seller with the highest late-delivery count is selected, and the inserted alert is returned for verification.

In [86]:

insert_alert_sql = """
WITH seller_late_orders AS (
    SELECT
        oi.seller_id,
        COUNT(DISTINCT oi.order_id) AS late_orders_count
    FROM olist_order_items AS oi
    JOIN olist_orders AS o
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_delivered_customer_date IS NOT NULL
      AND o.order_estimated_delivery_date IS NOT NULL
      AND o.order_delivered_customer_date::DATE
          > o.order_estimated_delivery_date::DATE
    GROUP BY oi.seller_id
)
INSERT INTO seller_alerts (
    seller_id,
    late_orders_count,
    alert_message
)
SELECT
    seller_id,
    late_orders_count,
    'Seller has the highest number of late deliveries'
FROM seller_late_orders
ORDER BY late_orders_count DESC, seller_id
LIMIT 1
RETURNING *;
"""

with engine.begin() as conn:
    result = conn.execute(text(insert_alert_sql))
    alert_df = pd.DataFrame(result.fetchall(), columns=result.keys())

display(alert_df)

,alert_id,seller_id,late_orders_count,alert_message,created_at
0,1,seller_007,17,Seller has the highest number of late deliveries,2026-10-25 19:33:11.291928

### Seller scoring with `INSERT ... ON CONFLICT DO UPDATE`

**Business question:** How can we maintain an up-to-date rating for each seller without creating duplicate records?

The `seller_score` table stores each seller's average review rating, review count, and rating tier.

Reviews are associated with orders rather than individual sellers. Therefore, we first create a distinct seller–order mapping to avoid multiplying review records when an order contains multiple items. We then aggregate the review data and use `ON CONFLICT DO UPDATE` to refresh existing seller scores.

In [87]:

create_seller_score_sql = """
CREATE TABLE IF NOT EXISTS seller_score (
    seller_id TEXT PRIMARY KEY REFERENCES olist_sellers(seller_id),
    avg_rating NUMERIC(3,2),
    n_reviews INTEGER NOT NULL DEFAULT 0 CHECK (n_reviews >= 0),
    tier TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

with engine.begin() as conn:
    conn.execute(text(create_seller_score_sql))

print("Seller score table created successfully.")

Seller score table created successfully.

In [88]:

upsert_seller_score_sql = """
WITH seller_orders AS (
    SELECT DISTINCT seller_id, order_id
    FROM olist_order_items
),
review_per_order AS (
    SELECT
        order_id,
        AVG(review_score)::NUMERIC(3,2) AS avg_rating,
        COUNT(review_score)::INTEGER AS n_reviews
    FROM olist_order_reviews
    GROUP BY order_id
),
seller_stats AS (
    SELECT
        so.seller_id,
        AVG(r.avg_rating)::NUMERIC(3,2) AS avg_rating,
        COALESCE(SUM(r.n_reviews), 0)::INTEGER AS n_reviews
    FROM seller_orders AS so
    LEFT JOIN review_per_order AS r
        ON r.order_id = so.order_id
    GROUP BY so.seller_id
)
INSERT INTO seller_score (
    seller_id,
    avg_rating,
    n_reviews,
    tier,
    updated_at
)
SELECT
    seller_id,
    avg_rating,
    n_reviews,
    CASE
        WHEN avg_rating IS NULL THEN NULL
        WHEN avg_rating >= 4.5 THEN 'excellent'
        WHEN avg_rating >= 4.0 THEN 'good'
        WHEN avg_rating >= 3.0 THEN 'average'
        ELSE 'needs_improvement'
    END,
    CURRENT_TIMESTAMP
FROM seller_stats
ON CONFLICT (seller_id)
DO UPDATE SET
    avg_rating = EXCLUDED.avg_rating,
    n_reviews = EXCLUDED.n_reviews,
    tier = EXCLUDED.tier,
    updated_at = CURRENT_TIMESTAMP
RETURNING *;
"""

with engine.begin() as conn:
    result = conn.execute(text(upsert_seller_score_sql))
    seller_score_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(seller_score_df)

     seller_id avg_rating  n_reviews       tier                 updated_at
0   seller_010       3.91         23    average 2026-10-25 19:33:11.333283
1   seller_013       4.10         20       good 2026-10-25 19:33:11.333283
2   seller_008       3.93         15    average 2026-10-25 19:33:11.333283
3   seller_014       4.22         27       good 2026-10-25 19:33:11.333283
4   seller_015       3.88         17    average 2026-10-25 19:33:11.333283
5   seller_003       4.50         22  excellent 2026-10-25 19:33:11.333283
6   seller_012       4.00         18       good 2026-10-25 19:33:11.333283
7   seller_011       4.19         16       good 2026-10-25 19:33:11.333283
8   seller_002       4.23         13       good 2026-10-25 19:33:11.333283
9   seller_018       4.07         30       good 2026-10-25 19:33:11.333283
10  seller_016       3.91         34    average 2026-10-25 19:33:11.333283
11  seller_006       3.88         24    average 2026-10-25 19:33:11.333283
12  seller_009       4.00         16       good 2026-10-25 19:33:11.333283
13  seller_001       4.15         20       good 2026-10-25 19:33:11.333283
14  seller_005       3.80         25    average 2026-10-25 19:33:11.333283
15  seller_017       3.63         19    average 2026-10-25 19:33:11.333283
16  seller_004       4.19         21       good 2026-10-25 19:33:11.333283
17  seller_007       3.96         25    average 2026-10-25 19:33:11.333283

### Updating delivery status with `UPDATE ... FROM`

**Business question:** Which orders were delivered later than their estimated delivery date?

We add an `is_late` Boolean column to the orders table. The `UPDATE ... FROM` statement calculates the delivery status for each order and updates the existing records.

An order is marked as late when its actual delivery date is later than its estimated delivery date. Orders that were not delivered or have missing delivery dates are marked as not late for this exercise.

In [89]:

update_late_sql = """
ALTER TABLE olist_orders
ADD COLUMN IF NOT EXISTS is_late BOOLEAN;

UPDATE olist_orders AS o
SET is_late = delivery_status.is_late
FROM (
    SELECT
        order_id,
        CASE
            WHEN order_status = 'delivered'
             AND order_delivered_customer_date IS NOT NULL
             AND order_estimated_delivery_date IS NOT NULL
             AND order_delivered_customer_date::DATE
                 > order_estimated_delivery_date::DATE
            THEN TRUE
            ELSE FALSE
        END AS is_late
    FROM olist_orders
) AS delivery_status
WHERE o.order_id = delivery_status.order_id;
"""

with engine.begin() as conn:
    conn.execute(text(update_late_sql))

    result = conn.execute(text("""
        SELECT
            COUNT(*) AS total_orders,
            COUNT(*) FILTER (WHERE is_late = TRUE) AS late_orders,
            COUNT(*) FILTER (WHERE is_late = FALSE) AS not_late_orders,
            COUNT(*) FILTER (WHERE is_late IS NULL) AS unknown_orders
        FROM olist_orders
    """))

    late_summary = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(late_summary)

   total_orders  late_orders  not_late_orders  unknown_orders
0           320          148              172               0

### Removing expired alerts with `DELETE ... RETURNING`

**Business question:** Which seller alerts are older than 30 days and should be removed?

The `DELETE ... RETURNING` statement deletes expired alerts and returns the deleted records for inspection. This makes it possible to verify which records were removed without running a separate query beforehand.

For this exercise, an alert is considered expired when its creation timestamp is more than 30 days old.

In [90]:

delete_old_alerts_sql = """
DELETE FROM seller_alerts
WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days'
RETURNING *;
"""

with engine.begin() as conn:
    result = conn.execute(text(delete_old_alerts_sql))
    deleted_alerts_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

print(f"Deleted alerts: {len(deleted_alerts_df)}")
display(deleted_alerts_df)

Deleted alerts: 0

Empty DataFrame
Columns: [alert_id, seller_id, late_orders_count, alert_message, created_at]
Index: []

## Customer Segmentation

Customer segmentation groups buyers according to their purchasing behavior. In this exercise, we use an RFM-style approach based on:

- **Recency:** how recently the customer made a purchase.
- **Frequency:** how many orders the customer placed.
- **Monetary value:** the total amount spent on order items and freight.

The segmentation is performed at the `customer_unique_id` level rather than the `customer_id` level, so multiple customer records belonging to the same buyer can be combined.

A reference date derived from the dataset is used instead of the current system date, making the results reproducible.

In [91]:

create_customer_dim_sql = """
CREATE TABLE IF NOT EXISTS olist_customer_dim (
    customer_unique_id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    customer_city TEXT,
    customer_state CHAR(2)
);

INSERT INTO olist_customer_dim (
    customer_unique_id,
    customer_id,
    customer_city,
    customer_state
)
SELECT DISTINCT ON (c.customer_unique_id)
    c.customer_unique_id,
    c.customer_id,
    c.customer_city,
    c.customer_state
FROM olist_customers AS c
LEFT JOIN olist_orders AS o
    ON o.customer_id = c.customer_id
ORDER BY
    c.customer_unique_id,
    o.order_purchase_timestamp DESC NULLS LAST,
    c.customer_id DESC
ON CONFLICT (customer_unique_id)
DO UPDATE SET
    customer_id = EXCLUDED.customer_id,
    customer_city = EXCLUDED.customer_city,
    customer_state = EXCLUDED.customer_state;
"""

with engine.begin() as conn:
    conn.execute(text(create_customer_dim_sql))

    result = conn.execute(text("""
        SELECT
            COUNT(*) AS unique_customers,
            COUNT(DISTINCT customer_unique_id) AS distinct_ids
        FROM olist_customer_dim
    """))

    print(pd.DataFrame(result.fetchall(), columns=result.keys()).to_string(index=False))

 unique_customers  distinct_ids
              126           126

### Building customer segments with RFM metrics

We calculate three customer-level metrics:

- **Recency:** number of days since the customer's most recent purchase.
- **Frequency:** number of distinct orders placed by the customer.
- **Monetary:** total spending on item prices and freight.

The reference date is set to one day after the latest purchase date in the dataset. This avoids using the current date and makes the segmentation reproducible.

Each customer is assigned a segment based on their purchasing activity. The table uses a unique constraint on `customer_unique_id` to prevent duplicate segment records.

In [92]:

create_segments_sql = """
CREATE TABLE IF NOT EXISTS customer_segments (
    segment_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_unique_id TEXT NOT NULL UNIQUE
        REFERENCES olist_customer_dim(customer_unique_id),
    recency_days INTEGER NOT NULL CHECK (recency_days >= 0),
    frequency INTEGER NOT NULL CHECK (frequency >= 0),
    monetary NUMERIC(12,2) NOT NULL CHECK (monetary >= 0),
    segment TEXT NOT NULL CHECK (
        segment IN ('VIP', 'regular', 'new', 'inactive')
    ),
    reference_date DATE NOT NULL
);

WITH reference AS (
    SELECT MAX(order_purchase_timestamp)::DATE + 1 AS reference_date
    FROM olist_orders
),
order_totals AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp,
        SUM(oi.price + oi.freight_value) AS order_total
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    WHERE o.order_status <> 'canceled'
      AND o.order_status <> 'unavailable'
    GROUP BY
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp
),
customer_metrics AS (
    SELECT
        c.customer_unique_id,
        r.reference_date,
        COALESCE(
            r.reference_date - MAX(ot.order_purchase_timestamp::DATE),
            r.reference_date - MIN(r.reference_date)
        )::INTEGER AS recency_days,
        COUNT(DISTINCT ot.order_id)::INTEGER AS frequency,
        COALESCE(SUM(ot.order_total), 0)::NUMERIC(12,2) AS monetary
    FROM olist_customer_dim AS c
    CROSS JOIN reference AS r
    LEFT JOIN order_totals AS ot
        ON ot.customer_id = c.customer_id
    GROUP BY c.customer_unique_id, r.reference_date
),
classified AS (
    SELECT
        customer_unique_id,
        recency_days,
        frequency,
        monetary,
        reference_date,
        CASE
            WHEN frequency >= 3
                 AND monetary >= 1000
                 AND recency_days <= 90
                THEN 'VIP'
            WHEN frequency >= 2
                THEN 'regular'
            WHEN frequency = 1
                 AND recency_days <= 90
                THEN 'new'
            ELSE 'inactive'
        END AS segment
    FROM customer_metrics
)
INSERT INTO customer_segments (
    customer_unique_id,
    recency_days,
    frequency,
    monetary,
    segment,
    reference_date
)
SELECT
    customer_unique_id,
    recency_days,
    frequency,
    monetary,
    segment,
    reference_date
FROM classified
ON CONFLICT (customer_unique_id)
DO UPDATE SET
    recency_days = EXCLUDED.recency_days,
    frequency = EXCLUDED.frequency,
    monetary = EXCLUDED.monetary,
    segment = EXCLUDED.segment,
    reference_date = EXCLUDED.reference_date;
"""

with engine.begin() as conn:
    conn.execute(text(create_segments_sql))

    result = conn.execute(text("""
        SELECT
            segment,
            COUNT(*) AS customer_count,
            ROUND(AVG(recency_days), 1) AS avg_recency_days,
            ROUND(AVG(frequency), 2) AS avg_frequency,
            ROUND(AVG(monetary), 2) AS avg_monetary
        FROM customer_segments
        GROUP BY segment
        ORDER BY customer_count DESC
    """))

    segments_df = pd.DataFrame(result.fetchall(), columns=result.keys())

display(segments_df)

    segment  customer_count avg_recency_days avg_frequency avg_monetary
0  inactive              59            209.9          0.66       316.96
1   regular              49            210.2          2.41      1232.91
2       new               9             49.1          1.00       442.59
3       VIP               9             40.3          3.22      2088.17

### INNER JOIN — Sales by State and Product Category

**Business question:** Which state–category combinations generate the highest sales?

The query joins orders, customers, order items, and products to calculate order counts, item counts, and total sales by customer state and product category.

In [93]:

inner_join_sql = """
SELECT
    c.customer_state,
    p.product_category_name,
    COUNT(DISTINCT o.order_id) AS order_count,
    COUNT(*) AS item_count,
    ROUND(SUM(oi.price + oi.freight_value), 2) AS total_sales
FROM olist_orders AS o
INNER JOIN olist_customers AS c
    ON o.customer_id = c.customer_id
INNER JOIN olist_order_items AS oi
    ON o.order_id = oi.order_id
INNER JOIN olist_products AS p
    ON oi.product_id = p.product_id
GROUP BY
    c.customer_state,
    p.product_category_name
ORDER BY total_sales DESC
LIMIT 15;
"""

with engine.connect() as conn:
    result = conn.execute(text(inner_join_sql))
    inner_join_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(inner_join_df)

   customer_state product_category_name  order_count  item_count total_sales
0              PR          garden_tools           26          28     8959.77
1              RS          garden_tools           19          23     8585.21
2              DF          garden_tools           14          17     8038.65
3              BA          garden_tools           13          14     6475.84
4              RJ          garden_tools           16          17     5483.55
5              SC          garden_tools           15          15     4731.55
6              RS         watches_gifts           16          16     4657.59
7              RS        bed_bath_table           10          11     4645.71
8              DF         watches_gifts            7           9     4265.65
9              RJ         watches_gifts           10          10     4143.06
10             MG          garden_tools           11          12     3950.46
11             PR         watches_gifts           11          12     3846.98
12             SP          garden_tools           13          15     3693.56
13             RS                  toys            9          10     3519.73
14             PR         health_beauty            8           8     3471.19

**Interpretation:** The highest sales in the displayed results come from garden tools in Paraná (PR), with 26 orders, 28 items, and total sales of 8,959.77. This illustrates why order counts and item counts should be tracked separately.

### LEFT JOIN — Customers Without Orders

**Business question:** Which customer records have no orders, and how much has each customer spent?

The query preserves all customers, including those without matching orders. `COALESCE` replaces missing order counts and spending totals with zero.

In [94]:

left_join_sql = """
SELECT
    c.customer_id,
    c.customer_unique_id,
    c.customer_state,
    COUNT(DISTINCT o.order_id) AS order_count,
    COALESCE(
        ROUND(SUM(oi.price + oi.freight_value), 2),
        0
    ) AS total_spent
FROM olist_customers AS c
LEFT JOIN olist_orders AS o
    ON c.customer_id = o.customer_id
LEFT JOIN olist_order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.customer_unique_id,
    c.customer_state
ORDER BY
    order_count ASC,
    c.customer_id
LIMIT 15;
"""

with engine.connect() as conn:
    result = conn.execute(text(left_join_sql))
    left_join_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(left_join_df)

   customer_id customer_unique_id customer_state  order_count total_spent
0   cust_00003           cu_00189             RJ            0           0
1   cust_00006           cu_00051             BA            0           0
2   cust_00007           cu_00115             RS            0           0
3   cust_00008           cu_00041             BA            0           0
4   cust_00020           cu_00137             PR            0           0
5   cust_00021           cu_00119             RS            0           0
6   cust_00031           cu_00175             RJ            0           0
7   cust_00032           cu_00098             DF            0           0
8   cust_00033           cu_00142             RJ            0           0
9   cust_00035           cu_00112             DF            0           0
10  cust_00039           cu_00154             DF            0           0
11  cust_00041           cu_00015             RJ            0           0
12  cust_00045           cu_00139             PR            0           0
13  cust_00053           cu_00055             MG            0           0
14  cust_00055           cu_00025             BA            0           0

**Interpretation:** Customer records without orders are retained with an order count and total spending of zero. `LEFT JOIN` preserves unmatched customers, while `COALESCE` replaces missing aggregate values with zero.

### FULL OUTER JOIN — Customers and Sellers by State

**Business question:** Which states have customers, sellers, or both?

The query aggregates customers and sellers by state, then combines both results using `FULL OUTER JOIN`. `COALESCE` ensures that states present on only one side are still displayed.

In [95]:

full_outer_join_sql = """
WITH customer_states AS (
    SELECT
        customer_state AS state,
        COUNT(*) AS customer_count
    FROM olist_customers
    GROUP BY customer_state
),
seller_states AS (
    SELECT
        seller_state AS state,
        COUNT(*) AS seller_count
    FROM olist_sellers
    GROUP BY seller_state
)
SELECT
    COALESCE(c.state, s.state) AS state,
    COALESCE(c.customer_count, 0) AS customer_count,
    COALESCE(s.seller_count, 0) AS seller_count
FROM customer_states AS c
FULL OUTER JOIN seller_states AS s
    ON c.state = s.state
ORDER BY state;
"""

with engine.connect() as conn:
    result = conn.execute(text(full_outer_join_sql))
    full_outer_join_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(full_outer_join_df)

  state  customer_count  seller_count
0    BA              23             3
1    DF              26             4
2    MG              16             0
3    PR              35             2
4    RJ              31             3
5    RS              39             0
6    SC              25             3
7    SP              25             3

**Interpretation:** The results show customers in all eight states, but no sellers in Minas Gerais (MG) or Rio Grande do Sul (RS). `FULL OUTER JOIN` preserves these states and `COALESCE` displays zero sellers instead of `NULL`.

### SELF JOIN — Customers in the Same State

**Business question:** Which pairs of distinct customers are located in the same state?

The query joins the customer table to itself using the state column. The condition `c1.customer_id < c2.customer_id` prevents matching a customer with themselves and avoids duplicate reversed pairs.

In [96]:

self_join_sql = """
SELECT
    c1.customer_id AS customer_1,
    c1.customer_city AS city_1,
    c1.customer_state AS state,
    c2.customer_id AS customer_2,
    c2.customer_city AS city_2
FROM olist_customers AS c1
INNER JOIN olist_customers AS c2
    ON c1.customer_state = c2.customer_state
   AND c1.customer_id < c2.customer_id
ORDER BY state, customer_1, customer_2
LIMIT 15;
"""

with engine.connect() as conn:
    result = conn.execute(text(self_join_sql))
    self_join_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(self_join_df)

    customer_1    city_1 state  customer_2            city_2
0   cust_00006  salvador    BA  cust_00008  feira de santana
1   cust_00006  salvador    BA  cust_00010          salvador
2   cust_00006  salvador    BA  cust_00016  feira de santana
3   cust_00006  salvador    BA  cust_00023  feira de santana
4   cust_00006  salvador    BA  cust_00025  feira de santana
5   cust_00006  salvador    BA  cust_00044          salvador
6   cust_00006  salvador    BA  cust_00054          salvador
7   cust_00006  salvador    BA  cust_00055  feira de santana
8   cust_00006  salvador    BA  cust_00066  feira de santana
9   cust_00006  salvador    BA  cust_00067  feira de santana
10  cust_00006  salvador    BA  cust_00075  feira de santana
11  cust_00006  salvador    BA  cust_00091          salvador
12  cust_00006  salvador    BA  cust_00098          salvador
13  cust_00006  salvador    BA  cust_00106  feira de santana
14  cust_00006  salvador    BA  cust_00118          salvador

**Interpretation:** The query identifies pairs of distinct customers in the same state. For example, customers from Salvador and Feira de Santana are both located in Bahia (BA). The ID comparison prevents self-matches and duplicate reversed pairs.

### Anti-Join — Orders Without Reviews

**Business question:** Which orders do not have an associated review?

The query uses `NOT EXISTS` to return orders for which no matching review record exists. This is useful for identifying missing feedback.

In [97]:

anti_join_sql = """
SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp
FROM olist_orders AS o
WHERE NOT EXISTS (
    SELECT 1
    FROM olist_order_reviews AS r
    WHERE r.order_id = o.order_id
)
ORDER BY o.order_purchase_timestamp DESC
LIMIT 15;
"""

with engine.connect() as conn:
    result = conn.execute(text(anti_join_sql))
    anti_join_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(anti_join_df)

        order_id order_status order_purchase_timestamp
0   order_000015    delivered      2018-09-01 16:00:00
1   order_000136    delivered      2018-08-14 23:00:00
2   order_000240    delivered      2018-08-14 11:00:00
3   order_000096    delivered      2018-07-14 07:00:00
4   order_000113  unavailable      2018-07-09 13:00:00
5   order_000296    delivered      2018-06-28 15:00:00
6   order_000016    delivered      2018-06-20 19:00:00
7   order_000082      shipped      2018-06-11 21:00:00
8   order_000310     canceled      2018-05-31 15:00:00
9   order_000138    delivered      2018-05-26 14:00:00
10  order_000145    delivered      2018-04-09 03:00:00
11  order_000228    delivered      2018-04-08 09:00:00
12  order_000226    delivered      2018-02-28 23:00:00
13  order_000083    delivered      2018-02-17 16:00:00
14  order_000173    delivered      2018-02-14 11:00:00

**Interpretation:** The query identifies orders without reviews, including orders with different statuses. `NOT EXISTS` checks for the absence of a matching review without multiplying order rows.

## Aggregate Analysis

Aggregate functions summarize data using calculations such as counts, averages, and sums. `WHERE` filters individual rows before grouping, while `HAVING` filters groups after aggregation.

### Seller Revenue Analysis

**Business question:** Which sellers generate the highest total sales value?

The query calculates the number of distinct orders and total item revenue, including freight, for each seller. `HAVING` keeps only sellers whose total sales exceed 5,000.

In [98]:

seller_agg_sql = """
SELECT
    oi.seller_id,
    COUNT(DISTINCT oi.order_id) AS order_count,
    COUNT(*) AS item_count,
    ROUND(SUM(oi.price + oi.freight_value), 2) AS total_sales,
    ROUND(AVG(oi.price + oi.freight_value), 2) AS avg_item_value
FROM olist_order_items AS oi
GROUP BY oi.seller_id
HAVING SUM(oi.price + oi.freight_value) > 5000
ORDER BY total_sales DESC;
"""

with engine.connect() as conn:
    result = conn.execute(text(seller_agg_sql))
    seller_agg_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(seller_agg_df)

     seller_id  order_count  item_count total_sales avg_item_value
0   seller_016           38          41    14553.26         354.96
1   seller_018           37          37    13808.73         373.21
2   seller_003           27          27    11514.24         426.45
3   seller_007           28          28    11268.23         402.44
4   seller_014           31          32    10834.80         338.59
5   seller_005           28          28    10261.61         366.49
6   seller_006           30          31    10117.71         326.38
7   seller_010           24          25    10051.57         402.06
8   seller_004           27          29     9773.73         337.03
9   seller_013           26          27     9202.32         340.83
10  seller_001           26          26     8859.45         340.75
11  seller_017           22          23     8424.27         366.27
12  seller_008           20          21     8114.01         386.38
13  seller_002           18          19     7408.89         389.94
14  seller_011           19          19     6552.00         344.84
15  seller_012           19          21     6361.59         302.93
16  seller_009           20          20     6264.94         313.25
17  seller_015           21          21     6124.92         291.66

**Interpretation:** Seller `seller_016` has the highest total sales at 14,553.26 across 38 orders and 41 items. The `HAVING` clause filters aggregated seller results to include only those with total sales above 5,000.

### Product Category Review Analysis

**Business question:** Which product categories have an average review score of at least 4.0?

The query joins order items, products, and reviews, then calculates the average review score and review count for each category. `HAVING` filters categories after aggregation.

In [99]:

category_reviews_sql = """
SELECT
    p.product_category_name,
    COUNT(DISTINCT r.review_id) AS review_count,
    ROUND(AVG(r.review_score), 2) AS avg_review_score
FROM olist_order_items AS oi
INNER JOIN olist_products AS p
    ON oi.product_id = p.product_id
INNER JOIN olist_order_reviews AS r
    ON oi.order_id = r.order_id
GROUP BY p.product_category_name
HAVING AVG(r.review_score) >= 4.0
ORDER BY avg_review_score DESC, review_count DESC;
"""

with engine.connect() as conn:
    result = conn.execute(text(category_reviews_sql))
    category_reviews_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(category_reviews_df)

      product_category_name  review_count avg_review_score
0                cool_stuff            19             4.47
1                      toys            31             4.28
2           furniture_decor            29             4.10
3  fashion_bags_accessories            37             4.08
4            bed_bath_table            23             4.08
5            sports_leisure            27             4.00

**Interpretation:** The `cool_stuff` category has the highest average review score (4.47 across 19 reviews). Six categories meet the minimum average score of 4.0. The `HAVING` clause filters categories based on their aggregated review scores.

### Seller Product Category Summary

**Business question:** Which product categories does each seller offer?

`STRING_AGG` combines distinct product category names into a single comma-separated string for each seller. `HAVING` keeps sellers associated with at least three distinct categories.

In [100]:

string_agg_sql = """
SELECT
    s.seller_id,
    COUNT(DISTINCT p.product_category_name) AS category_count,
    STRING_AGG(
        DISTINCT p.product_category_name,
        ', ' ORDER BY p.product_category_name
    ) AS product_categories
FROM olist_sellers AS s
JOIN olist_order_items AS oi
    ON s.seller_id = oi.seller_id
JOIN olist_products AS p
    ON oi.product_id = p.product_id
GROUP BY s.seller_id
HAVING COUNT(DISTINCT p.product_category_name) >= 3
ORDER BY category_count DESC, s.seller_id;
"""

with engine.connect() as conn:
    result = conn.execute(text(string_agg_sql))
    string_agg_df = pd.DataFrame(
        result.fetchall(),
        columns=result.keys()
    )

display(string_agg_df)

,seller_id,category_count,product_categories
0,seller_001,10,"bed_bath_table, computers_accessories, cool_st..."
1,seller_007,10,"bed_bath_table, computers_accessories, cool_st..."
2,seller_016,10,"bed_bath_table, computers_accessories, cool_st..."
3,seller_002,9,"bed_bath_table, computers_accessories, fashion..."
4,seller_005,9,"bed_bath_table, computers_accessories, fashion..."
5,seller_006,9,"computers_accessories, cool_stuff, fashion_bag..."
6,seller_014,9,"bed_bath_table, cool_stuff, fashion_bags_acces..."
7,seller_018,9,"bed_bath_table, cool_stuff, fashion_bags_acces..."
8,seller_003,8,"bed_bath_table, computers_accessories, cool_st..."
9,seller_010,8,"bed_bath_table, computers_accessories, fashion..."
10,seller_015,8,"computers_accessories, fashion_bags_accessorie..."
11,seller_017,8,"cool_stuff, fashion_bags_accessories, furnitur..."
12,seller_004,7,"fashion_bags_accessories, furniture_decor, gar..."
13,seller_008,7,"bed_bath_table, computers_accessories, fashion..."
14,seller_009,7,"bed_bath_table, cool_stuff, fashion_bags_acces..."
15,seller_011,7,"computers_accessories, cool_stuff, fashion_bag..."
16,seller_012,7,"bed_bath_table, computers_accessories, fashion..."
17,seller_013,6,"bed_bath_table, fashion_bags_accessories, gard..."

**Interpretation:** Sellers `seller_001`, `seller_007`, and `seller_016` are associated with the highest number of distinct product categories (10 each). `STRING_AGG` combines the category names into a readable list, while `HAVING` excludes sellers associated with fewer than three categories.

## Set Operations

### UNION — States with Customers or Sellers

**Business question:** Which states appear in either the customer or seller data?

`UNION` combines the results of two queries and removes duplicate states. This is appropriate because we need a list of unique states rather than a list containing repeated values.

In [101]:

union_sql = """
SELECT customer_state AS state
FROM olist_customers

UNION

SELECT seller_state AS state
FROM olist_sellers

ORDER BY state;
"""

with engine.connect() as conn:
    result = conn.execute(text(union_sql))
    union_df = pd.DataFrame(result.fetchall(), columns=result.keys())

display(union_df)

  state
0    BA
1    DF
2    MG
3    PR
4    RJ
5    RS
6    SC
7    SP

**Interpretation:** The query returns eight distinct states represented in the customer or seller data. `UNION` removes duplicates, so each state appears only once.

### Window Function — Latest Order per Customer

**Business question:** What is the most recent order for each unique customer?

`ROW_NUMBER()` ranks each customer's orders from newest to oldest. Filtering for `row_num = 1` returns one latest order per customer.

In [102]:

window_sql = """
WITH ranked_orders AS (
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_unique_id
            ORDER BY o.order_purchase_timestamp DESC, o.order_id DESC
        ) AS row_num
    FROM olist_customers AS c
    JOIN olist_orders AS o
        ON c.customer_id = o.customer_id
)
SELECT
    customer_unique_id,
    order_id,
    order_status,
    order_purchase_timestamp
FROM ranked_orders
WHERE row_num = 1
ORDER BY order_purchase_timestamp DESC
LIMIT 15;
"""

with engine.connect() as conn:
    result = conn.execute(text(window_sql))
    window_df = pd.DataFrame(result.fetchall(), columns=result.keys())

display(window_df)

   customer_unique_id      order_id order_status order_purchase_timestamp
0            cu_00187  order_000141    delivered      2018-10-11 21:00:00
1            cu_00063  order_000151   processing      2018-10-07 06:00:00
2            cu_00132  order_000305    delivered      2018-10-06 09:00:00
3            cu_00179  order_000314    delivered      2018-10-06 08:00:00
4            cu_00141  order_000224    delivered      2018-10-03 03:00:00
5            cu_00075  order_000122    delivered      2018-10-01 12:00:00
6            cu_00171  order_000268      shipped      2018-09-28 11:00:00
7            cu_00139  order_000207   processing      2018-09-28 04:00:00
8            cu_00068  order_000012      shipped      2018-09-25 14:00:00
9            cu_00070  order_000259    delivered      2018-09-24 14:00:00
10           cu_00165  order_000255    delivered      2018-09-23 07:00:00
11           cu_00114  order_000167    delivered      2018-09-22 19:00:00
12           cu_00123  order_000195    delivered      2018-09-06 17:00:00
13           cu_00186  order_000101   processing      2018-08-24 08:00:00
14           cu_00107  order_000060    delivered      2018-08-22 18:00:00

**Interpretation:** The query returns the latest order for each unique customer. `ROW_NUMBER()` ranks orders within each customer group, preventing customers with multiple orders from appearing more than once in the final result.

## Reflection

The most challenging JOIN was the FULL OUTER JOIN because it required preserving states present in either the customer or seller data. It helped identify states with customers but no sellers. The most useful business question was customer segmentation because it combines purchasing recency, frequency, and monetary value into actionable customer groups.

For production ETL pipelines, I find `ON CONFLICT DO UPDATE` particularly useful because it allows derived metrics to be refreshed without creating duplicate records. Constraints and `RETURNING` are also valuable for maintaining data integrity and verifying data modifications.

Window functions can support machine learning pipelines by ranking customer transactions, selecting the latest record, and calculating historical behavioral features. These features can help prepare consistent datasets for model training.

Several data quality considerations appeared in this exercise. Some orders have no associated reviews, delivery timestamps may be missing, and one order can contain multiple items or sellers. These relationships must be handled carefully to avoid incorrect counts and duplicated aggregates.

The `customer_unique_id` is more appropriate than `customer_id` for customer-level segmentation because multiple customer records can belong to the same buyer. Using `customer_id` alone could split one buyer's purchasing history into separate segments.

Finally, seller scoring requires a distinct seller–order mapping because an order may contain multiple items from the same seller. Without controlling the seller–order grain, joins can multiply review records and distort calculated ratings. However, order-level reviews cannot reliably measure individual seller performance when an order includes multiple sellers, so this remains a limitation of the simplified model.